development:
  adapter: postgresql
  encoding: unicode
  database: saidit_development
  pool: 5
  username: John
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: saidit_test
  pool: 5
  username: John
  password: