# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca61fb9d8e4c6021610a420fade71bdbe14c9e0296a662b660d3e1ca0ce2dc968cf8ccf86209e6704fc95d72a3ec0d9ae6f7d257c8bb33feb8117c134b7cce43

test:
  secret_key_base: c2e6e9faf63655d5c89ffa09e2e3a4f98f58e13a46401bd8c76efd48032f7c86278cf19935069469956977d0c2e6d90a5d6ca17b2e10ceb5f8321da11f352777

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
